project05/config/routes.rb
Articles::Application.routes.draw do
  resources :authors

  resources :articles

  
  root :to => 'articles#index'

end

project05/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	attr_accessor :new_author_name
	
	cattr_reader :per_page
	@@per_page = 10
	
	validates :title, :body, presence: true
	
	before_update :increment_edits
	before_save :create_new_author
	
	private
		def increment_edits
			self.edits = self.edits + 1
		end
	
		def create_new_author
			create_author(:name => new_author_name) unless new_author_name.blank?
		end
end

project05/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :articles
	validate :name_not_pat
	validates :name, presence: true
	
	has_attached_file :photo,
		:styles => { :thumb => "100x100#", :small => "150x150>" }
		
	private
		def name_not_pat
			if name.downcase.include? "pat"
				errors.add(:name, 'Pat is not allowed anywhere in the string, in any case!')
			end
		end
end

project05/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

project05/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate :page => params[:page], :order => 'id DESC', :include => :author

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

project05/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

project05/app/helpers/application_helper.rb
module ApplicationHelper
end

project05/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_mailto(display, article)
    mail_to '', display,
      :subject => 'Artic.le: ' + article.title,
      :body    => 'Check out this article on Artic.le, ' + link_to(article.title, polymorphic_url(article)),
      :class   => 'text-image',
      :title   => 'Send article to a friend'
  end
end

project05/app/helpers/authors_helper.rb
module AuthorsHelper
end

project05/app/views/articles/_article.html.haml
%tr
  %td{:title => article.title}= h truncate(article.title, :length => 35)
  %td= h article.author.name
  %td= h truncate(article.body, :length => 30)
  %td= h article.created_at.to_s(:created_date)
  %td
    = link_to 'Show', article, :title => 'Show Article'
    = link_to 'Edit', edit_article_path(article), :title => 'Edit Article'
    = link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete, :title => 'Delete this article'
    = article_mailto 'E-mail', article

project05/app/views/articles/_form.html.erb
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author, size: 40 %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, rows: 10, cols: 60 %>
  </div>

project05/app/views/articles/_form.html.haml
%li
  = f.label :title
  = f.text_field :title, :size => 64
%li
  = f.label :author_id
  = f.collection_select :author_id, Author.all, :id, :name, :prompt => "Select an Author"
  %br
  Or Create New Author
  %br
  = f.text_field :new_author_name
%li
  = f.label :body
  = f.text_area :body, :cols => 64, :rows => 25

project05/app/views/articles/edit.html.erb
<h1>Articl.es</h1>
<p>...not just for the country of Spain</p>

<p><%= link_to_function 'Back', "history.back()", :title => 'Go Back' %></p>

<h2>Editing article</h2>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= render 'form' %>
  <div class="actions">
    <%= f.submit 'Create', :title => 'Create article' %>
  </div>
<% end %>

project05/app/views/articles/edit.html.haml
%h3
  Articl.es
%p
  \...not just for the country of Spain

= link_to_function 'Back', "history.back()", :title => 'Go Back'

%h2
  Editing "#{@article.title}"

- if @article.errors.any?
  = @article.errors.full_messages

= form_for(@article) do |f|
  = field_set_tag nil, :id => 'scaffold' do
    %ol
      = render :partial => "form", :locals => {:f => f}
      %li
        = f.label :submit, "%nbsp;"
        = f.submit "Submit Changes"

project05/app/views/articles/index.html.erb
<h1>Articl.es</h1>
<p>...with a name .com hipsters love!</p>

<h2>All the World's Articles</h2>

<%= link_to 'New Article', new_article_path, :title => 'Create a New Article!' %>

<div class="articleList">

<% if @articles.count > 0 %>
<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Body</th>
	<th>Creation Date</th>
  </tr>
<% @articles.each do |article| %>
  <tr class="<%= cycle("even","odd") %>">
    <td><%= article.title %></td>
	<td><%= article.author %></td>
	<td><%= article.body.truncate(40) %></td>
	<td><%= article.created_at.to_s(:created_date) %></td>
	
    <td><%= link_to 'Show', article, :title => 'Show this article' %></td>
    <td><%= link_to 'Edit', edit_article_path(article), :title => 'Edit this article' %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete, :title => 'Delete this article' %></td>
  </tr>
<% end %>
</table>
</div>

<%= pluralize(@articles.count, 'article') %>
<% else %>
<p>Be the first to write an article!</p>
<% end %>
<br />

project05/app/views/articles/index.html.haml
%h1
  Articl.es
%p
  \...with a name .com hipsters love!

%h3
  All the World's Articles

%p
  = link_to 'New Article', new_article_path, :title => 'Create a New Article!'

.pagination
  = will_paginate @articles
  
#table-wrapper
  %table#articles
    %thead
      %th Title
      %th Author
      %th Body
      %th Creation Date
      %th
    %tbody
      - unless @articles.empty?
        = render @articles
      - else
        %tr
          %td{:colspan => "5"} There are no articles, be the first to write one!

%span#article_count
  = pluralize(@articles.count, 'article')
  
.pagination
  = will_paginate @articles
  
= link_to 'Authors', authors_path

project05/app/views/articles/new.html.erb
<h1>Articl.es</h1>
<p>...not just for the country of Spain</p>

<p><%= link_to 'Back', articles_path, :title => 'Back to list of Articles' %></p>

<h2>New article</h2>

<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= render 'form' %>
  <div class="actions">
    <%= f.submit 'Create', :title => 'Create article' %>
  </div>
<% end %>

project05/app/views/articles/new.html.haml
%h1
  Articl.es
%p
  \...not just for the country of Spain

%p
  = link_to 'Back', articles_path, :title => 'Back to list of Articles'

%h2
  New article

- if @article.errors.any?
  = @article.errors.full_messages

= form_for(@article) do |f|
  = field_set_tag nil, :id => 'scaffold' do
    %ol
      = render :partial => "form", :locals => {:f => f}
      %li
        = f.label :submit
        = f.submit 'Create Article'

project05/app/views/articles/show.html.erb
<h1>Articl.es</h1>
<p>...what is &quot;Articl&quot; in Spanish anyway?</p>

<p id="notice"><%= notice %></p>

<%= link_to 'Back', articles_path, :title => 'Back to list of Articles' %> | 
<%= link_to 'Edit', edit_article_path(@article), :title => 'Edit Article' %> | 
<%= link_to 'Destroy', @article, confirm: 'Are you sure?', method: :delete, :title => 'Delete this article' %> |
<%= article_mailto 'E-mail', @article %>

<h2> <%= @article.title %> </h2>

<p>By <%= @article.author %>. <%= @article.edits %> edits since <%= @article.created_at.to_s(:created_day) %></p>

<%= simple_format(@article.body) %>

<br />

project05/app/views/articles/show.html.haml
%h1
  Articl.es
  
%p
  \...what is &quot;Articl&quot; in Spanish anyway?

= link_to 'Back', articles_path, :title => 'Back to list of Articles'
= link_to 'Edit', edit_article_path(@article), :title => 'Edit Article'
= link_to 'Destroy', @article, confirm: 'Are you sure?', method: :delete, :title => 'Delete this article'
= article_mailto 'E-mail', @article

%h2
  = @article.title

%p
  By 
  = link_to @article.author.name, @article.author, :title => 'View Author'
  \. 
  = @article.edits
  edits since
  = @article.created_at.to_s(:created_day)

= simple_format(@article.body)

project05/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project05/app/views/authors/_form.html.haml
%li
  = f.label :name
  = f.text_field :name
%li
  = f.label :photo
  = f.file_field :photo

project05/app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

project05/app/views/authors/edit.html.haml
%h1 Editing author

- if @author.errors.any?
  = @author.errors.full_messages


= form_for(@author, :html => { :multipart => true }) do |f|
  = field_set_tag nil, :id => 'scaffold' do
    %ol
      = render :partial => "form", :locals => {:f => f}
      %li
        = f.submit 'Update'

= link_to 'Show', @author
= link_to 'Back', authors_path

project05/app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author', new_author_path %>

project05/app/views/authors/index.html.haml
%h1 Listing authors

#table-wrapper
  %table#authors
    %thead
      %th Name
      %th Articles
    %tbody
      - unless @authors.empty?
        - @authors.each do |a|
          %tr
            %td= h a.name
            %td= h a.articles.count
            %td
              = link_to 'Show', a
              = link_to 'Edit', edit_author_path(a)
              = link_to 'Destroy', a, confirm: 'Are you sure?', method: :delete, :title => 'Delete this author'
      - else
        %tr
          %td{:colspan => "5"} There are no authors, be the first to write!

= link_to 'New Author', new_author_path

= link_to 'Articles', articles_path

project05/app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

project05/app/views/authors/new.html.haml
%h1 New Author
- form_for(@author, :html => {multipart => true}) do |f|
  - field_set_tag nil, :id => 'scaffold' do
    = f.error_messages
    %ol
      = render :partial => "form", :locals => {:f => f}
      %li
        = f.submit 'Create'

= link_to 'Back', authors_path

project05/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

project05/app/views/authors/show.html.haml
%div{:id => 'author_block'}
  - if @author.photo?
    %img{:src => @author.photo.url(:thumb)}
  %span.clear &nbsp;
  %h3= h @author.name
  
%div
  - if @author.articles.any?
    - @author.articles.each do |ar|
      %div=link_to ar.title, article_path(ar)
  -else
    %div==#{h @author.name} has not written any articles\.  He's a bum\!

= link_to 'Edit', edit_author_path(@author)
= link_to 'Back', authors_path

project05/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Articles</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>